ALTER TABLE `Contains`
  ADD CONSTRAINT `Contains_ibfk_2` FOREIGN KEY (`Card_id`) REFERENCES `Customer` (`Card_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Contains_ibfk_3` FOREIGN KEY (`DateTime`) REFERENCES `Transaction` (`DateTime`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Contains_ibfk_4` FOREIGN KEY (`Barcode`) REFERENCES `Product` (`Barcode`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `E_mail`
  ADD CONSTRAINT `E_mail_ibfk_1` FOREIGN KEY (`Card_id`) REFERENCES `Customer` (`Card_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Has`
  ADD CONSTRAINT `Has_ibfk_1` FOREIGN KEY (`Store_id`) REFERENCES `Store` (`Store_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Has_ibfk_2` FOREIGN KEY (`Category_name`) REFERENCES `Category` (`Category_name`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `History`
  ADD CONSTRAINT `History_ibfk_1` FOREIGN KEY (`Barcode`) REFERENCES `Product` (`Barcode`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Offers`
  ADD CONSTRAINT `Offers_ibfk_1` FOREIGN KEY (`Store_id`) REFERENCES `Store` (`Store_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Offers_ibfk_2` FOREIGN KEY (`Barcode`) REFERENCES `Product` (`Barcode`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Phone_C`
  ADD CONSTRAINT `Phone_C_ibfk_1` FOREIGN KEY (`Card_id`) REFERENCES `Customer` (`Card_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Phone_S`
  ADD CONSTRAINT `Phone_S_ibfk_1` FOREIGN KEY (`Store_id`) REFERENCES `Store` (`Store_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Product`
  ADD CONSTRAINT `Product_ibfk_1` FOREIGN KEY (`Category_name`) REFERENCES `Category` (`Category_name`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Transaction`
  ADD CONSTRAINT `Transaction_ibfk_1` FOREIGN KEY (`Card_id`) REFERENCES `Customer` (`Card_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Transaction_ibfk_2` FOREIGN KEY (`Store_id`) REFERENCES `Store` (`Store_id`) ON DELETE CASCADE ON UPDATE CASCADE;
